---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - Фильтр цены не должен принимать отрицательные значения
  - На сайте должна присутствовать возможность регистрации новых пользователей 
  - На сайте должна присутствовать возможность авторизации пользователей
  - При нажатии на кнопки "Следующая" и "Предыдущая" в нижней части тела страницы, страница должна возвращаться наверх
  - На сайте должна присутсвовать кнопка сброса всех фильтров поиска
  - После очистки корзины сайт не должен возвращать кэшированые данные с сервера после обновления страницы корзины
  - После успешного оформления заказа корзина должна очищаться
